
name : html/css
  on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

   workflow_dispatch:
jobs:
  build: 
    runs-on: ubuntu-latest
  steps:
      name : Integration
      uses: actions/checkout@v4
          

      
