name: Deploy to Production Server
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: self-hosted
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PEM21_KEY }}
          port: 22
          script: |
            cd /var/www/html/vertixxx
            # Fix directory permissions
            sudo chown -R ubuntu:ubuntu .
            sudo chmod -R 755 .
            # Clean git state
            git reset --hard
            git clean -fd
            # Set correct remote URL (using HTTPS with token)
            git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/thiruvenkadam5/Vertix_bos.git
            # Pull changes
            git config --global --add safe.directory /var/www/html/vertixxx
            git pull origin main
            # Fix any remaining permissions
            sudo chown -R ubuntu:ubuntu .
            echo "Deployment completed successfully!"
            - name: Send error email
             if: failure()
                 uses: dawidd6/action-send-mail@v3
                 with:
                   server_address: smtp.gmail.com
                   server_port: 587
                   username: ${{ secrets.EMAIL_USERNAME }}
                   subject: ❌ GitHub Action Failed
                   to: sangeetha.p@hepl.com
                   from: GitHub Actions <thiruvenkdam.b@hepl.com>
                   body: |
                     ❗ CI/CD pipeline failed on branch: ${{ github.ref }}
                     🔍 Check the job here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
