name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Use SSH checkout instead of HTTPS
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PEM21_KEY }}
          port: 22
          script: |
            cd /var/www/html/vertixxx
            # Fix directory ownership (temporarily to ubuntu for Git operations)
            sudo chown -R ubuntu:ubuntu .
            # Pull changes using SSH (safer than HTTPS + token)
            git remote set-url origin git@github.com:thiruvenkadam5/Vertix_bos.git
            git config --global --add safe.directory /var/www/html/vertixxx
            git reset --hard
            git clean -fd
            git pull origin main
            # Restore ownership to www-data (for web server)
            #sudo chown -R www-data:www-data .
            echo "✅ Deployment completed successfully!"
