name: Deploy to Production Server
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PEM21_KEY }}
          port: 22
          script: |
            cd /var/www/html/vertixxx
            # Fix directory permissions
            sudo chown -R ubuntu:ubuntu .
            sudo chmod -R 755 .
            # Clean git state
            git reset --hard
            git clean -fd
            # Set correct remote URL (using HTTPS with token)
            git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/thiruvenkadam5/Vertix_bos.git
            # Pull changes
            git config --global --add safe.directory /var/www/html/vertixxx
            git pull origin main
            # Fix any remaining permissions
            sudo chown -R ubuntu:ubuntu .
            echo "Deployment completed successfully!"
          
          
