name: satrt deploy 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, label-1]  # Corrected syntax

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


