name: HTML-CSS
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: self-hosted
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: Setup SSH for GitHub
        run: |
          mkdir -p ~/.ssh
          # echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          # chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          chmod 644  ~/.ssh/known_hosts
 
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PEM21_KEY }}
          port: 22
          script: | 
            cd /var/www/html/vertixxx
             git branch
             # git pull origin main
           
