    name: Deploy to Server

    on:
      push:
        branches:
          - main

    jobs:
      deploy:
        runs-on: self-hosted
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Run deployment script
            run: |
              # Replace with your deployment commands
              echo "Deploying..."
               scp -r ./* root@ip-172-31-47-30:/var/www/html/vertix_bos
               ssh root@ip-172-31-47-30 "cd /var/www/html/vertix_bos"
            shell: bash
